modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Nokunami/Elementus/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://modrinth.com/mod/iIDoDiAj" #optional
logoFile="elementus_logo.png" #optional
credits="Xaidee of TeamGelena for Armor Trim mixin" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${neo_version_range}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="farmersdelight"
mandatory=false
versionRange="[1.20.1-1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="piercingpaxels"
mandatory=false
versionRange="[1.0.,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="nethersdelight"
mandatory=false
versionRange="[1.20.1-4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
mandatory=false
versionRange="[1.20.1-3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aether"
mandatory=false
versionRange="[1.20.1-1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simplyswords"
mandatory=false
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=false
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sniffsweapons"
mandatory=false
versionRange="[1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="advancednetherite"
mandatory=false
versionRange="[2,)"
ordering="AFTER"
side="BOTH"